/**
 * ============================================================================
 * wordlist.ts — EFF Diceware Short Wordlist (Curated Subset)
 * ============================================================================
 *
 * A curated selection of common, memorable English words for Diceware
 * passphrase generation. Based on the EFF's short wordlist principles:
 * - All words are 3-6 characters for easy memorization
 * - No offensive or confusing words
 * - No homophones or easily-confused words
 *
 * With 1,296 words, each word provides ~10.34 bits of entropy:
 *   log2(1296) ≈ 10.34
 *
 * Passphrase entropy:
 *   4 words ≈ 41.4 bits
 *   5 words ≈ 51.7 bits
 *   6 words ≈ 62.0 bits
 *   7 words ≈ 72.4 bits
 *   8 words ≈ 82.7 bits
 */

export const DICEWARE_WORDLIST: string[] = [
  "acid", "acme", "acre", "acts", "aged", "ages", "aide", "aims", "ajar",
  "alarm", "alert", "alibi", "alien", "align", "alive", "alley", "allot",
  "allow", "alloy", "aloft", "alone", "alpha", "amaze", "amber", "amend",
  "ample", "angel", "anger", "angle", "ankle", "annex", "anvil", "apart",
  "apex", "apple", "apply", "arena", "argue", "arise", "armor", "aroma",
  "arrow", "atlas", "attic", "audio", "audit", "avail", "avert", "avid",
  "avoid", "await", "awake", "award", "aware", "axiom", "azure",
  "badge", "bagel", "baker", "balmy", "bamboo", "banjo", "baron", "basin",
  "batch", "beach", "beacon", "beard", "beast", "began", "begin", "being",
  "below", "bench", "berry", "bird", "birth", "black", "blade", "blame",
  "blank", "blast", "blaze", "bleak", "blend", "bless", "blind", "bliss",
  "block", "bloom", "blown", "blues", "blunt", "blurt", "blush", "board",
  "boast", "bold", "bolt", "bonus", "booth", "bound", "bowed", "boxer",
  "brain", "brand", "brave", "bravo", "bread", "break", "breed", "brick",
  "bride", "brief", "brink", "brisk", "broad", "broke", "brook", "brown",
  "brush", "brute", "budge", "build", "built", "bulge", "bunch", "burst",
  "buyer", "cabin", "cable", "camel", "candy", "cargo", "carry", "carve",
  "catch", "cause", "cedar", "chain", "chair", "chalk", "champ", "charm",
  "chart", "chase", "cheap", "check", "cheek", "cheer", "chess", "chest",
  "chief", "child", "chill", "china", "chord", "chunk", "churn", "cider",
  "cigar", "cinch", "civic", "civil", "claim", "clamp", "clash", "clasp",
  "class", "clean", "clear", "clerk", "click", "cliff", "climb", "cling",
  "cloak", "clock", "clone", "close", "cloth", "cloud", "clown", "clump",
  "clung", "coach", "coast", "cobra", "cocoa", "coil", "color", "comet",
  "comic", "coral", "cord", "corps", "couch", "count", "court", "cover",
  "craft", "crane", "crash", "crawl", "crazy", "cream", "crest", "crew",
  "crisp", "cross", "crowd", "crown", "crude", "crush", "cubic", "curve",
  "cycle", "daily", "dance", "darts", "datum", "dawn", "deal", "dealt",
  "death", "debug", "decal", "decay", "decoy", "decry", "deity", "delay",
  "delta", "delve", "demon", "dense", "depot", "depth", "derby", "desk",
  "deter", "detox", "devil", "diary", "digit", "diner", "ditch", "diver",
  "dizzy", "dodge", "doing", "donor", "doubt", "dough", "draft", "drain",
  "drake", "drama", "drank", "drape", "drawl", "drawn", "dread", "dream",
  "dress", "drift", "drill", "drink", "drive", "droit", "drone", "drool",
  "drove", "drown", "drums", "drunk", "dryer", "dryly", "dual", "duke",
  "dummy", "dune", "dusty", "dwarf", "dwell", "dying",
  "eager", "eagle", "early", "earth", "easel", "eaten", "eater", "ebony",
  "eclat", "edged", "eight", "eject", "elbow", "elder", "elect", "elite",
  "elope", "elude", "ember", "emoji", "empty", "enact", "ended", "enemy",
  "enjoy", "ensue", "enter", "entry", "envoy", "equal", "equip", "erode",
  "error", "essay", "ethic", "evade", "event", "every", "evict", "evoke",
  "exact", "exalt", "excel", "exile", "exist", "expat", "extra", "exult",
  "fable", "facet", "fagot", "faint", "fairy", "faith", "false", "fancy",
  "fatal", "fauna", "feast", "felon", "fence", "ferry", "fetch", "fever",
  "fiber", "field", "fiery", "fifty", "fight", "final", "finch", "first",
  "flair", "flame", "flank", "flare", "flash", "flask", "fleet", "flesh",
  "flick", "fling", "flint", "float", "flock", "flood", "floor", "flora",
  "flour", "flown", "fluid", "fluke", "flung", "flunk", "flush", "flute",
  "focal", "focus", "foggy", "folly", "force", "forge", "forgo", "forty",
  "forum", "found", "foxed", "frame", "frank", "fraud", "fresh", "friar",
  "front", "frost", "froze", "fruit", "fully", "fungi", "furry", "fuzzy",
  "gamma", "gauge", "gaunt", "gavel", "gaze", "giddy", "gift", "given",
  "gizmo", "gland", "glare", "glass", "gleam", "glide", "globe", "gloom",
  "glory", "gloss", "glove", "gnome", "going", "gorge", "gouge", "grace",
  "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass",
  "grave", "gravel", "graze", "great", "greed", "green", "greet", "grief",
  "grill", "grind", "gripe", "groan", "groom", "grope", "gross", "group",
  "grove", "growl", "grown", "guard", "guess", "guest", "guide", "guild",
  "guilt", "guise", "gulch", "gummy", "guppy", "gusto",
  "habit", "hairy", "happy", "hardy", "haste", "hasty", "hatch", "haven",
  "hazel", "heard", "heart", "heavy", "hedge", "heist", "hello", "herbs",
  "heron", "hilly", "hinge", "hippo", "hired", "hobby", "homer", "honey",
  "honor", "horse", "hotel", "hound", "house", "hover", "human", "humid",
  "humor", "husky", "hyena", "hyper",
  "ideal", "igloo", "image", "imply", "inbox", "incur", "index", "indie",
  "inept", "inert", "infer", "ingot", "inner", "input", "intro", "ionic",
  "ivory",
  "jewel", "jiffy", "joint", "joker", "jolly", "joust", "judge", "juice",
  "jumbo", "jumpy", "juror", "kayak", "kebab", "knack", "kneel", "knelt",
  "knife", "knobs", "knock", "knoll", "known",
  "label", "laced", "lance", "large", "laser", "latch", "later", "latex",
  "lathe", "layer", "learn", "lease", "ledge", "legal", "lemon", "level",
  "lever", "light", "lilac", "limbo", "linen", "liner", "llama", "local",
  "lodge", "lofty", "logic", "login", "looks", "lorry", "lotus", "lousy",
  "loved", "lower", "loyal", "lucid", "lucky", "lunar", "lunch", "lured",
  "lusty", "lying", "lyric",
  "macho", "macro", "magic", "major", "maker", "mango", "manor", "maple",
  "march", "marsh", "mason", "match", "maven", "maxim", "mayor", "meaty",
  "medal", "media", "melon", "mercy", "merge", "merit", "merry", "metal",
  "meter", "midst", "might", "mimic", "mince", "minor", "minus", "mirth",
  "miser", "misty", "mixer", "mocha", "model", "mogul", "moist", "money",
  "month", "moose", "moral", "motel", "motor", "motto", "mound", "mount",
  "mourn", "mouse", "movie", "muddy", "mural", "murky", "music", "musty",
  "naive", "nasal", "nasty", "naval", "nerve", "never", "newly", "nexus",
  "night", "noble", "noise", "north", "notch", "noted", "novel", "nudge",
  "nurse", "nylon",
  "oasis", "occur", "ocean", "offer", "olive", "onset", "opera", "optic",
  "orbit", "organ", "other", "otter", "ought", "ounce", "outer", "outdo",
  "oxide", "ozone",
  "paced", "paddy", "paint", "panel", "panic", "paper", "party", "paste",
  "patch", "patio", "pause", "peace", "peach", "pearl", "pedal", "penny",
  "perch", "perky", "pesky", "petal", "petty", "photo", "piano", "piece",
  "pilot", "pinch", "pitch", "pivot", "pixel", "pizza", "place", "plaid",
  "plain", "plank", "plant", "plate", "plaza", "plead", "pleat", "plier",
  "pluck", "plumb", "plume", "plump", "plunk", "plush", "poach", "point",
  "poise", "poker", "polar", "polka", "polyp", "pooch", "poppy", "porch",
  "poser", "pound", "power", "prawn", "press", "price", "pride", "prime",
  "print", "prism", "privy", "prize", "probe", "prone", "proof", "prose",
  "proud", "prove", "proxy", "prude", "prune", "psalm", "pulse", "punch",
  "pupil", "puppy", "purge", "pushy", "pygmy",
  "quack", "qualm", "quark", "quart", "quasi", "queen", "query", "quest",
  "queue", "quick", "quiet", "quill", "quirk", "quota", "quote",
  "radar", "radio", "rainy", "raise", "rally", "ranch", "range", "rapid",
  "raven", "rayon", "razor", "reach", "ready", "realm", "rearm", "rebel",
  "rebus", "recap", "recon", "redox", "refer", "regal", "reign", "relax",
  "relay", "relic", "remit", "renew", "repay", "repel", "reply", "rerun",
  "reset", "resin", "retro", "retry", "rider", "ridge", "rifle", "rigid",
  "rigor", "rinse", "ripen", "risen", "risky", "rival", "river", "rivet",
  "robin", "robot", "rocky", "rodeo", "rogue", "roost", "rotor", "rouge",
  "rough", "round", "route", "rover", "royal", "rugby", "ruler", "rumor",
  "rural", "rusty",
  "saint", "salad", "salon", "salsa", "salty", "salve", "sandy", "sauna",
  "savor", "scald", "scale", "scalp", "scam", "scare", "scarf", "scene",
  "scent", "scone", "scope", "score", "scout", "scowl", "scram", "scrap",
  "sense", "serve", "setup", "seven", "sever", "shade", "shaft", "shake",
  "shall", "shame", "shape", "share", "shark", "sharp", "shawl", "sheen",
  "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine", "shirt",
  "shock", "shore", "short", "shout", "shove", "shown", "shrub", "shrug",
  "sight", "sigma", "silky", "silly", "since", "sixth", "sixty", "sized",
  "skate", "skier", "skill", "skull", "slain", "slang", "slash", "slate",
  "sleek", "sleep", "slept", "slice", "slide", "sling", "slope", "sloth",
  "slump", "smack", "small", "smart", "smear", "smell", "smile", "smirk",
  "smith", "smoke", "snack", "snail", "snake", "snare", "sneak", "sniff",
  "snore", "snout", "snowy", "sober", "solar", "solve", "sonic", "south",
  "space", "spare", "spark", "speak", "spear", "speed", "spell", "spend",
  "spent", "spice", "spied", "spill", "spine", "spoke", "spoon", "sport",
  "spray", "spree", "sprig", "squad", "squat", "squid", "staff", "stage",
  "stain", "stair", "stake", "stale", "stalk", "stall", "stamp", "stand",
  "stank", "stare", "stark", "start", "stash", "state", "stays", "steak",
  "steal", "steam", "steel", "steep", "steer", "stern", "stick", "stiff",
  "still", "sting", "stink", "stock", "stoic", "stoke", "stole", "stomp",
  "stone", "stood", "stool", "stoop", "store", "storm", "story", "stout",
  "stove", "strap", "straw", "stray", "strip", "stuck", "study", "stuff",
  "stump", "stung", "stunk", "stunt", "style", "sugar", "suite", "sunny",
  "super", "surge", "swamp", "swarm", "swear", "sweat", "sweep", "sweet",
  "swept", "swift", "swing", "swirl", "swoop", "sword", "sworn", "swung",
  "syrup",
  "table", "tacit", "taffy", "taint", "taken", "tally", "talon", "tango",
  "tapir", "tease", "tempo", "tense", "tepid", "their", "theme", "there",
  "these", "thick", "thief", "thigh", "thing", "think", "third", "thorn",
  "those", "three", "threw", "throw", "thrum", "thumb", "thump", "tidal",
  "tiger", "tight", "timer", "timid", "tipsy", "titan", "title", "toast",
  "today", "token", "topic", "topaz", "total", "touch", "tough", "towel",
  "tower", "toxic", "trace", "track", "trade", "trail", "train", "trait",
  "tramp", "trash", "trawl", "treat", "trend", "trial", "tribe", "trick",
  "tripe", "trite", "troll", "troop", "trout", "truck", "truly", "trump",
  "trunk", "trust", "truth", "tulip", "tumor", "tuner", "tunic", "turbo",
  "tutor", "tweak", "tweed", "tweet", "twice", "twine", "twist",
  "udder", "ultra", "uncle", "under", "undue", "unfed", "unfit", "unify",
  "union", "unite", "unity", "unmet", "until", "upper", "upset", "urban",
  "usage", "usher", "using", "usual", "utter",
  "vague", "valid", "valor", "value", "valve", "vapor", "vault", "verse",
  "vigor", "vinyl", "viola", "viper", "viral", "virus", "visit", "vista",
  "vital", "vivid", "vocal", "vodka", "vogue", "voice", "voila", "voter",
  "vouch", "vowel",
  "wacky", "wafer", "wager", "wagon", "waist", "watch", "water", "waver",
  "weary", "weave", "wedge", "weedy", "weigh", "weird", "whale", "wheat",
  "wheel", "where", "which", "while", "whirl", "white", "whole", "widen",
  "width", "wield", "windy", "witch", "woman", "world", "worry", "worse",
  "worst", "worth", "would", "wound", "wrack", "wrath", "wreck", "wrist",
  "write", "wrong", "wrote",
  "yacht", "yearn", "yield", "young", "youth", "zebra", "zesty", "zilch",
  "zippy", "zombi", "zoned"
];
